name = "Lax47"
defaultTargets = ["Lax47"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "c5ea00351c28e24afc9f0f84379aa41082b1188f"

[[require]]
name = "Lax51"
git = "https://github.com/szymtor/RAM-TM"
rev = "4f6c21aae81fbe8d1233d3ae8358b82b110549b9"
subDir = "concepts"

[[lean_lib]]
name = "Lax47"
