name = "Lax405409Proofs"
defaultTargets = ["Lax405409Proofs"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "Lax405409"
path = "../concepts"

[[require]]
name = "Lax296731Proofs"
git = "https://github.com/EdouardBonnet/moser-tardos"
rev = "2fc19f8c69c3ae6dc8770629b3613220283ce669"
subDir = "proofs"

[[require]]
name = "Lax296731"
git = "https://github.com/EdouardBonnet/moser-tardos"
rev = "2fc19f8c69c3ae6dc8770629b3613220283ce669"
subDir = "concepts"

[[require]]
name = "Lax759944Proofs"
git = "https://github.com/szymtor/RAM-TM"
rev = "13530db8ae9e82025c8874656ae54ccfcecba566"
subDir = "proofs"

[[require]]
name = "Lax808846Proofs"
git = "https://github.com/lax-archive/lax-submissions"
rev = "9394e531cc51cb67a0214bca3f9264dfe97ba5c7"
subDir = "word-ram/proofs"

[[lean_lib]]
name = "Lax405409Proofs"
