name = "Lax47Proofs"
defaultTargets = ["Lax47Proofs"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "c5ea00351c28e24afc9f0f84379aa41082b1188f"

[[require]]
name = "Lax47"
path = "../concepts"

[[require]]
name = "Lax41Proofs"
git = "https://github.com/EdouardBonnet/moser-tardos"
rev = "05704ee2deb398d84129c1e2c3a961f29fec0bed"
subDir = "proofs"

[[require]]
name = "Lax51Proofs"
git = "https://github.com/szymtor/RAM-TM"
rev = "4f6c21aae81fbe8d1233d3ae8358b82b110549b9"
subDir = "proofs"

[[require]]
name = "Lax13Proofs"
git = "https://github.com/lax-archive/lax-submissions"
rev = "d35ba57ad420ce6a6d3c763aa7f6a4a8be1d406d"
subDir = "word-ram/proofs"

[[lean_lib]]
name = "Lax47Proofs"
