name = "Lax47Proofs"
defaultTargets = ["Lax47Proofs"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "Lax47"
path = "../concepts"

[[require]]
name = "Lax296731"
git = "https://github.com/EdouardBonnet/moser-tardos"
rev = "96597ce451d880dffa5b5dac0eb01b40d8065bb9"
subDir = "concepts"

[[require]]
name = "Lax296731Proofs"
git = "https://github.com/EdouardBonnet/moser-tardos"
rev = "96597ce451d880dffa5b5dac0eb01b40d8065bb9"
subDir = "proofs"

[[require]]
name = "Lax759944"
git = "https://github.com/szymtor/RAM-TM"
rev = "134e398cef46599371df99f10c9007bc34ba3868"
subDir = "concepts"

[[require]]
name = "Lax759944Proofs"
git = "https://github.com/szymtor/RAM-TM"
rev = "134e398cef46599371df99f10c9007bc34ba3868"
subDir = "proofs"

[[require]]
name = "Lax253009"
git = "https://github.com/EdouardBonnet/lax-253009"
rev = "36990a6252e73a45c2dfc55024d9b457fc1ca934"
subDir = "concepts"

[[require]]
name = "Lax253009Proofs"
git = "https://github.com/EdouardBonnet/lax-253009"
rev = "36990a6252e73a45c2dfc55024d9b457fc1ca934"
subDir = "proofs"

[[lean_lib]]
name = "Lax47Proofs"
